#!/bin/sh
#
# $FreeBSD: ports/net/freeradius2/files/radiusd.sh.in,v 1.8 2012/01/14 08:56:14 dougb Exp $
#
# PROVIDE: radiusd
# REQUIRE: NETWORKING SERVERS slapd mysql postgresql
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable radiusd:
#
# radiusd_enable="YES"
#

. /etc/rc.subr

name=radiusd
rcvar=radiusd_enable
load_rc_config $name

command=/usr/local/sbin/radiusd

# In debug mode, radiusd doesn't create a pid file, so comment pidfile and
# let rc.subr use a process check on procname (which defaults to command).
#pidfile=/var/run/radiusd/radiusd.pid

extra_commands="reload debug"
debug_cmd="radiusd_debug"


# The radiusd_config parameter is now obsolete. Instead, derive the
# configuration directory name from radiusd_flags if possible, otherwise
# default to /usr/local/etc/raddb
required_dirs=`echo ${radiusd_flags} | sed -Ene 's:.*\-[^[:space:]d]*d[[:space:]]*([^[:space:]]+).*:\1:p'`
required_dirs=${required_dirs:-"/usr/local/etc/raddb"}

required_files="${required_dirs}/radiusd.conf"

radiusd_enable=${radiusd_enable-"NO"}

command_args="&"

radiusd_debug()
{
    radiusd_flags="-X ${radiusd_flags}"
    run_rc_command start
}


run_rc_command "$1"
