<?php
$hotspot_errors['block']['tr'] = 'Cihazınızın erişimi engellenmiştir.';
$hotspot_errors['block']['en'] = 'Your device is banned.';
$hotspot_errors['block']['de'] = 'Ihr Gerät ist verboten.';
$hotspot_errors['block']['ru'] = 'Вас забанили';

$hotspot_errors['login']['tr'] = 'Hatalı veri girdiniz.';
$hotspot_errors['login']['en'] = 'Invalid credentials.';
$hotspot_errors['login']['de'] = 'ungültige Anmeldeinformationen.';
$hotspot_errors['login']['ru'] = 'недействительные учетные данные.';

$hotspot_errors['session']['tr'] = 'Oturumunuz zaten açık durumda.';
$hotspot_errors['session']['en'] = 'You are already logged in.';
$hotspot_errors['session']['de'] = 'Sie sind bereits angemeldet.';
$hotspot_errors['session']['ru']  = 'Вы авторизованы уже.';
?>